export default Object.freeze({
	LISTINGS: "Listings",
	LISTING_DETAILS: "ListingDetails",
	LISTING_EDIT: "ListingEdit",
	LOGIN: "Connexion",
	MESSAGES: "Messages",
	REGISTER: "Inscription",
	POLICY: "Policy",
	PROFILE: "Profile",
	CANDIDATURES: "Candidatures",
	CANDIDATURE: "Candidature",
	DISCOVER_ESEAC: "University",
	DISCOVER_IPSAS: "UniversityScreenIpsas",
	DISCOVER_LASALL: "UniversityScreenLasall",
	DISCOVER_COUNTRY: "Country",
	TUNISIE_EN_BREF: "TunisieEnBref",
	INFO_UTILES: "InfoUtiles",
	POSTULER: "Postuler",
	INSESEAC: "InsEseac",
	INSIPSAS: "InsIpsas",
	INSLASALL: "InsLasall",
	FDESEAC: "fdEseac",
	FDIPSAS: "fdIpsas",
	FDLASALL: "fdlasall",
	ALLCANDIDATS: "CandidatureAdmin",

});
